field: bb99de79-0344-407e-9e92-6dffaa48a5dc # Form Listing
fieldLayouts:
  57967811-5824-469e-84e1-e1f47c4aa879:
    tabs:
      -
        elements:
          -
            fieldUid: 98cb052b-55e3-4fc0-be85-87706556b7a7 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 02cfd546-2a5a-4c8d-adfd-05a147f44f96 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f5e76fac-d559-4107-8681-23c7a7cbc0f0 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  02cfd546-2a5a-4c8d-adfd-05a147f44f96: # Heading
    columnSuffix: pqmqpevm
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  98cb052b-55e3-4fc0-be85-87706556b7a7: # Icon
    columnSuffix: osfrcqxz
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      columnType: text
      iconSets: '*'
      remoteSets: ''
      showLabels: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\iconpicker\fields\IconPickerField
  f5e76fac-d559-4107-8681-23c7a7cbc0f0: # Text
    columnSuffix: wuaxclfh
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: lists
name: Lists
sortOrder: 1
