field: 30dcaead-f602-4a31-bab1-91a7b6672d1f # Cta Builder
fieldLayouts:
  8ff12afe-d090-4523-969d-91ba81782036:
    tabs:
      -
        elements:
          -
            fieldUid: 863622c9-e888-4686-a749-8d46f45a8576 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: efd3cf89-cb48-418b-9181-cd0e196b1150 # Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  863622c9-e888-4686-a749-8d46f45a8576: # Heading
    columnSuffix: jodvkpfb
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  efd3cf89-cb48-418b-9181-cd0e196b1150: # Number
    columnSuffix: crrxxocz
    contentColumnType: text
    fieldGroup: null
    handle: number
    instructions: ''
    name: Number
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: statistic
name: Statistic
sortOrder: 1
