field: b3e9295f-bd1a-41d9-aa0a-f612c72c5647 # Statistics
fieldLayouts:
  2afb7494-2e24-4192-a069-0d14207a22b4:
    tabs:
      -
        elements:
          -
            fieldUid: 218c71d7-fdaa-426a-a3ed-237d10fcdea1 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b59fa7bc-9f51-48ff-ba98-1b40677d968d # Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b26c3904-e4ee-4748-9513-42975e85cfe8 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  218c71d7-fdaa-426a-a3ed-237d10fcdea1: # Icon
    columnSuffix: sxcbpnez
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: true
    settings:
      columnType: text
      iconSets:
        - 'font:Flaticon.woff'
        - 'font:themify.woff'
      remoteSets: ''
      showLabels: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\iconpicker\fields\IconPickerField
  b26c3904-e4ee-4748-9513-42975e85cfe8: # Heading
    columnSuffix: pdcmecox
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  b59fa7bc-9f51-48ff-ba98-1b40677d968d: # Number
    columnSuffix: ohpyjfbj
    contentColumnType: integer(10)
    fieldGroup: null
    handle: number
    instructions: ''
    name: Number
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
handle: statistic
name: Statistic
sortOrder: 1
