handle: mainNavigation
instructions: ''
maxNodes: ''
name: 'Main Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagateNodes: false
siteSettings:
  2c2850f7-4457-45d8-8ae0-65a4c01bc69f: # Mechanicsburg Eye
    enabled: '1'
  11d77e24-a31c-4f20-8dff-6f54b85283df: # York Eye
    enabled: '1'
  89ec2dbc-b44f-40d8-b224-548937d554dc: # Carlislevision Care
    enabled: '1'
  425199fc-1a4f-4a25-ab29-66c431ff91db: # Wheatlyn Eyecare
    enabled: '1'
sortOrder: 1
structure:
  maxLevels: null
  uid: 5437a57f-9e8b-4397-a653-faaf9c7a2e14
