baseUrl: $THIRD_SITE_URL
enabled: true
handle: carlislevisionCare
hasUrls: true
language: en-US
name: 'Carlislevision Care'
primary: false
siteGroup: d056edb3-0b8c-4a3e-8b47-f29e2476ac30 # Sanspareil Eyecare
sortOrder: 3
