childBlocks:
  - advanceSlider
field: e3a4a8ab-6d19-4f3e-9ace-88e1460b5b5f # Hero
handle: advanceSliders
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Advance Sliders'
sortOrder: 2
topLevel: true
