childBlocks: ''
field: 30dcaead-f602-4a31-bab1-91a7b6672d1f # Cta Builder
fieldLayouts:
  427ce1d2-cb0f-4f84-b9b5-a4a7b315d000:
    tabs:
      -
        elements:
          -
            fieldUid: dfd2434c-49f9-41af-ad36-28194fa72ffb # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd44fb60-ae69-47ed-9211-8382d7d7efdb # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9946fa71-feae-4847-bce7-29c8d4b1003f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 579622ad-24b8-4af6-b960-64573012dbce # Mobile Number
            instructions: ''
            label: 'Phone Number'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 099894d9-8f0c-4956-97d7-7a78d417bea5 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0a53dbd8-7522-43e6-8f8b-663c3913d340 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2b2b8169-8666-4b51-a8fd-6a529c04c854 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: ctaNormal
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: CTA
sortOrder: 3
topLevel: true
