childBlocks:
  - imageContentWithListing
  - imageContentWithSidenote
  - imageContentWithVideo
  - imageContentWithFullWidth
  - imageContentWithTestimonial
field: 5fd03c49-057d-404f-bf92-e78039e66854 # Page Builder
handle: imageContent
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Image Content'
sortOrder: 11
topLevel: true
