childBlocks: ''
field: 5fd03c49-057d-404f-bf92-e78039e66854 # Page Builder
fieldLayouts:
  6cd25ecf-e9df-412d-bdc0-9509e08ec09a:
    tabs:
      -
        elements:
          -
            fieldUid: b6b8ab40-fc5e-4326-98ac-afb361279ea8 # Logo
            instructions: ''
            label: 'Logo Images'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0a53dbd8-7522-43e6-8f8b-663c3913d340 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 99fe12b8-19d0-442d-a184-3f035c8fd3a8 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 78e12444-c096-4f24-9160-02f33964e5d6 # Margin Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 820beb7b-ccbe-4ce2-a95d-e8143d49cf51 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 59c47b1d-4f47-4d7d-bb97-72df688c6a1b # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Spacing
        sortOrder: 3
handle: logos
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Logos
sortOrder: 27
topLevel: true
