childBlocks:
  - simpleSlider
field: e3a4a8ab-6d19-4f3e-9ace-88e1460b5b5f # Hero
handle: simpleSilders
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Simple Silders'
sortOrder: 6
topLevel: true
