childBlocks: ''
field: e3a4a8ab-6d19-4f3e-9ace-88e1460b5b5f # Hero
fieldLayouts:
  64caa8ab-d350-4db2-8905-b6e9744b471a:
    tabs:
      -
        elements:
          -
            fieldUid: 2b2b8169-8666-4b51-a8fd-6a529c04c854 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd44fb60-ae69-47ed-9211-8382d7d7efdb # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: simpleHero
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Simple Hero'
sortOrder: 10
topLevel: true
