childBlocks: ''
field: 30dcaead-f602-4a31-bab1-91a7b6672d1f # Cta Builder
fieldLayouts:
  1bd5a13b-ebe7-4840-a495-00537c0230c7:
    tabs:
      -
        elements:
          -
            fieldUid: 62ad7736-18a8-4f92-8634-a8d4c7949bfc # Main Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3e9295f-bd1a-41d9-aa0a-f612c72c5647 # Statistics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 0a53dbd8-7522-43e6-8f8b-663c3913d340 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: statistics
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Statistics
sortOrder: 1
topLevel: true
