childBlocks:
  - tab
field: 5fd03c49-057d-404f-bf92-e78039e66854 # Page Builder
fieldLayouts:
  4456cb5a-d6a7-4f9e-82b5-1c6452cfe4a5:
    tabs:
      -
        elements:
          -
            fieldUid: 99fe12b8-19d0-442d-a184-3f035c8fd3a8 # Margin Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 78e12444-c096-4f24-9160-02f33964e5d6 # Margin Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 820beb7b-ccbe-4ce2-a95d-e8143d49cf51 # Padding Top
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 59c47b1d-4f47-4d7d-bb97-72df688c6a1b # Padding Bottom
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Spacing
        sortOrder: 1
handle: tabbedContent
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Tabbed Content'
sortOrder: 30
topLevel: true
