columnSuffix: cfxsnrab
contentColumnType: text
fieldGroup: e8c8a29f-6c66-46de-907b-c52b4d890d10 # Global
handle: address
instructions: ''
name: Address
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
