columnSuffix: null
contentColumnType: string
fieldGroup: 8a88dc9e-d347-45fd-91a5-516debdcb33d # Neo
handle: buttons
instructions: ''
name: Buttons
searchable: false
settings:
  contentTable: '{{%matrixcontent_buttons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
