columnSuffix: uvosfgap
contentColumnType: text
fieldGroup: 742cee9e-0d18-4762-858d-adb0b404d053 # Common
handle: designation
instructions: ''
name: Designation
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
