columnSuffix: ooltgjus
contentColumnType: string
fieldGroup: 8a88dc9e-d347-45fd-91a5-516debdcb33d # Neo
handle: imageSize
instructions: ''
name: 'Image Size'
searchable: false
settings:
  genError: null
  json: null
  multi: false
  template: _sdf/imageSize.json
  templateData: null
translationKeyFormat: null
translationMethod: site
type: amici\SuperDynamicFields\fields\SueprDynamicDropdownField
