columnSuffix: null
contentColumnType: string
fieldGroup: 8a88dc9e-d347-45fd-91a5-516debdcb33d # Neo
handle: listing
instructions: ''
name: Listing
searchable: false
settings:
  contentTable: '{{%matrixcontent_listing}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
