columnSuffix: wyznbmvl
contentColumnType: text
fieldGroup: 8a88dc9e-d347-45fd-91a5-516debdcb33d # Neo
handle: map
instructions: ''
name: Map
searchable: false
settings:
  boundary: '""'
  boundaryRestrictionNELat: null
  boundaryRestrictionNELng: null
  boundaryRestrictionSWLat: null
  boundaryRestrictionSWLng: null
  country: null
  countryRestriction: null
  height: null
  hideAddress: ''
  hideLatLng: null
  hideMap: ''
  hideSearch: ''
  lat: 51.272154
  lng: 0.514951
  maxZoom: '18'
  minZoom: '3'
  showCurrentLocation: ''
  showLatLng: '1'
  showW3WField: false
  showW3WGrid: false
  size: normal
  typeRestriction: null
  zoom: 15
translationKeyFormat: null
translationMethod: site
type: ether\simplemap\fields\MapField
