columnSuffix: null
contentColumnType: string
fieldGroup: 742cee9e-0d18-4762-858d-adb0b404d053 # Common
handle: pageBuilder
instructions: ''
name: 'Page Builder'
searchable: true
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
