columnSuffix: null
contentColumnType: string
fieldGroup: e8c8a29f-6c66-46de-907b-c52b4d890d10 # Global
handle: socialLinks
instructions: ''
name: 'Social Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sociallinks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
