columnSuffix: null
contentColumnType: string
fieldGroup: 8a88dc9e-d347-45fd-91a5-516debdcb33d # Neo
handle: statistics
instructions: ''
name: Statistics
searchable: true
settings:
  contentTable: '{{%matrixcontent_statistics_1}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
