fieldLayouts:
  ebac4878-cf7d-4a31-b47b-9c37674eedf4:
    tabs:
      -
        elements:
          -
            fieldUid: 2b2b8169-8666-4b51-a8fd-6a529c04c854 # Background Image
            instructions: ''
            label: 'Static Simple Hero Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf1b0da2-ab9e-4cef-b91e-f3c797dd6a8b # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: general
name: General
sortOrder: 3
